//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimsonCoward.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullFoodMenu
    {
        public string Description { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public System.Guid CategoryID { get; set; }
        public string CatName { get; set; }
        public string CatDesc { get; set; }
    }
}
