//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimsonCoward.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeTip
    {
        public System.Guid Id { get; set; }
        public byte[] image { get; set; }
        public string link { get; set; }
        public string title { get; set; }
        public string text1 { get; set; }
        public string text2 { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
    }
}
