//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimsonCoward.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyImage
    {
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public string Extension { get; set; }
        public Nullable<bool> ShowAsFirstImage { get; set; }
        public string PRL { get; set; }
        public string PropertyType { get; set; }
        public string PropertyFor { get; set; }
        public string Qadaa { get; set; }
        public string District { get; set; }
        public Nullable<int> Size { get; set; }
    }
}
