//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimsonCoward.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstateProperty
    {
        public string PRL { get; set; }
        public string Qadaa { get; set; }
        public string District { get; set; }
        public string PropertyFor { get; set; }
        public string PropertyType { get; set; }
        public string Neighborhood { get; set; }
        public string Quality { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<int> Receptions { get; set; }
        public Nullable<int> TotalBedrooms { get; set; }
        public Nullable<int> Bathrooms { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<bool> Exclusive { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> TotalFloor { get; set; }
        public Nullable<int> FamilyRoom { get; set; }
        public Nullable<int> MasterBedRooms { get; set; }
        public Nullable<int> Parkings { get; set; }
        public Nullable<int> RentPrice { get; set; }
        public Nullable<int> SalePrice { get; set; }
        public Nullable<int> BldChargesPerMonth { get; set; }
        public string AdditionalInformation { get; set; }
        public string Web_GuideDescription { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Pending { get; set; }
        public Nullable<bool> Closed { get; set; }
        public string Zone { get; set; }
        public string ZoneNbr { get; set; }
        public string ZoningDescription { get; set; }
        public Nullable<int> DriverRoom { get; set; }
        public Nullable<int> MaidRoom { get; set; }
        public Nullable<int> DiningRoom { get; set; }
        public Nullable<int> Kitchen { get; set; }
        public Nullable<int> MaidBathRoom { get; set; }
        public Nullable<bool> ShowOnFirstPage { get; set; }
        public Nullable<bool> Generator { get; set; }
        public Nullable<bool> Furnished { get; set; }
        public string AgentName { get; set; }
        public string Department { get; set; }
        public string Country { get; set; }
        public string Features { get; set; }
        public string MapLong { get; set; }
        public string MapLat { get; set; }
    }
}
